### ISSUE TITLE
demo is broken

### ISSUE THREAD

**Issue by tmpvar** [gl-vis/gl-spikes3d#1]
![screen shot 2014-10-28 at 8 00 36 pm](https://cloud.githubusercontent.com/assets/46673/4820534/cc5743f0-5f17-11e4-9fe5-9355c24fee72.png)

// @maxharris9

**Comment by mikolalysenko** [comment]
Uh oh, taking a look.

**Comment by mikolalysenko** [comment]
That seems like a bug in poly2tri in vectorize-text.  If you update to the latest version it should be fixed.
